name: "vcf_stats"
description: Generate bcftools statistics from VCF files for MultiQC reporting
keywords:
  - vcf
  - variants
  - bcftools
  - multiqc
tools:
  - bcftools:
      description: "BCFtools is a set of utilities that manipulate variant calls in VCF and BCF format"
      homepage: "https://samtools.github.io/bcftools/"
      documentation: "https://samtools.github.io/bcftools/bcftools.html"
      doi: "10.1093/bioinformatics/btp352"
      licence: ["MIT"]
      identifier: "biotools:bcftools"
input:
  - - meta:
        type: map
        description: Groovy Map containing sample and caller information
    - vcf:
        type: file
        description: Input VCF
        pattern: "*.vcf.gz"
output:
  stats:
    - - meta:
          type: map
          description: Groovy Map containing sample and caller information
      - "*.bcftools_stats.txt":
          type: file
          description: BCFtools stats report
          pattern: "*.bcftools_stats.txt"
  mqc:
    - - meta:
          type: map
          description: Groovy Map containing sample and caller information
      - "*_mqc.tsv":
          type: file
          description: MultiQC custom-content table with per-sample variant counts
          pattern: "*_mqc.tsv"
  versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"
authors:
  - "@atacportray"
maintainers:
  - "@atacportray"
